-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 09:53:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `nombre` TEXT(20) NOT NULL,
  `apellido` TEXT(15) NOT NULL,
  `banner` LONGTEXT NULL,
  `sobremi` LONGTEXT NULL,
  `fotoPerfil` VARCHAR(10) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Experiencia` (
  `idExperiencia` INT NOT NULL,
  `logoEmpresa` VARCHAR(10) NOT NULL,
  `inicio` VARCHAR(15) NOT NULL,
  `fin` VARCHAR(15) NOT NULL,
  `nombreEmpresa` TEXT(15) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idExperiencia`),
  INDEX `fk_Experiencia_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Experiencia_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Educacion` (
  `idEducacion` INT NOT NULL,
  `escudonstitucion` VARCHAR(45) NOT NULL,
  `inicio` VARCHAR(15) NOT NULL,
  `fin` VARCHAR(15) NOT NULL,
  `tituloObtenido` MEDIUMTEXT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idEducacion`),
  INDEX `fk_Educacion_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Educacion_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `idProyectos` INT NOT NULL,
  `logoProyecto` VARCHAR(45) NOT NULL,
  `inicio` VARCHAR(15) NOT NULL,
  `fin` VARCHAR(15) NOT NULL,
  `nombreProyecto` MEDIUMTEXT NOT NULL,
  `grupoDeTrabajo` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idProyectos`),
  INDEX `fk_Proyectos_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Proyectos_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habilidades` (
  `idHabilidades` INT NOT NULL,
  `iconoPrograma` VARCHAR(45) NOT NULL,
  `porcentajeConocimiento` VARCHAR(10) NOT NULL,
  `nombrePrograma` TEXT(10) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idHabilidades`),
  INDEX `fk_Habilidades_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Habilidades_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
